[package]
name = "scheduler"
version = "0.1.0"
authors = ["Szymon Urba≈õ <szymon.urbas@aol.com>"]

[dependencies]
rand = "0.3.15"
cursive = { git = "https://github.com/gyscos/Cursive", features = [ "ncurses-backend" ] }
